spring:
  application:
    name: business-rental
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.168.93:8848
#        server-addr: nacos.funtl.com:80

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:9001/oauth/token
      user-authorization-uri: http://localhost:9001/oauth/authorize
    resource:
      token-info-uri: http://localhost:9001/oauth/check_token

dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.business.controller
  registry:
    address: nacos://192.168.168.93
    port: 8848
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  provider:
    timeout: 2500
#  protocol:
#    name: dubbo
#    port: -1
#    serialization: kryo
#  registry:
#    address: nacos://nacos.funtl.com
#    port: 80

server:
  port: 9004

management:
  endpoints:
    web:
      exposure:
        include: "*"
