#spring:
#  application:
#    name: business-reg
#  main:
#    allow-bean-definition-overriding: true
#  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
#  cloud:
#    nacos:
#      discovery:
#        server-addr: nacos.funtl.com:80
#
#dubbo:
#  scan:
#    base-packages: com.funtl.myshop.plus.business.controller
#  protocol:
#    name: dubbo
#    port: -1
#    serialization: kryo
#  registry:
#    address: nacos://nacos.funtl.com
#    port: 80
spring:
  application:
    name: business-reg
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.168.93:8848

dubbo:
  scan:
    base-packages: com.funtl.myshop.plus.business.controller
  registry:
    address: nacos://192.168.168.93
    port: 8848
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  provider:
    timeout: 2500

server:
  # ${random.int[9000,9999]} 随机端口
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
